menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/zero2hex

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus: spherez
duoshuo:

# Analytics
# google-analytics:
ga: UA-84373425-1

# Copyright Infomation
startyear: 2016
